export const browserCoreExamples = [
  "localclaw browser status",
  "localclaw browser start",
  "localclaw browser stop",
  "localclaw browser tabs",
  "localclaw browser open https://example.com",
  "localclaw browser focus abcd1234",
  "localclaw browser close abcd1234",
  "localclaw browser screenshot",
  "localclaw browser screenshot --full-page",
  "localclaw browser screenshot --ref 12",
  "localclaw browser snapshot",
  "localclaw browser snapshot --format aria --limit 200",
  "localclaw browser snapshot --efficient",
  "localclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "localclaw browser navigate https://example.com",
  "localclaw browser resize 1280 720",
  "localclaw browser click 12 --double",
  'localclaw browser type 23 "hello" --submit',
  "localclaw browser press Enter",
  "localclaw browser hover 44",
  "localclaw browser drag 10 11",
  "localclaw browser select 9 OptionA OptionB",
  "localclaw browser upload /tmp/file.pdf",
  'localclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "localclaw browser dialog --accept",
  'localclaw browser wait --text "Done"',
  "localclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "localclaw browser console --level error",
  "localclaw browser pdf",
];
